sudo: required

language: go

go:
  - 1.11.x
  
services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

install:
  - echo "Please don't go get"

script:
  - TAG=${TRAVIS_TAG:-latest} make build

before_deploy:
- echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

deploy:
  provider: script
  script: TAG=$TRAVIS_TAG make push manifest
  on:
    tags: true
